/* =======================================================
 *
 * Created by anele on 03/09/2026.
 *
 * @anele_ace
 *
 * =======================================================
 */

import './globals.css'
import type { Metadata } from 'next'
import { getSiteSettings } from '@/lib/payload'
import { Geist, Geist_Mono } from 'next/font/google'
import { SiteHeader, SiteFooter } from '@/components'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    viewport: null
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const siteSettings = await getSiteSettings()

  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
    <head>
        <meta charSet="UTF-8" />
        <link rel="icon" type="image/svg+xml" href="/icon.svg" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1.0, user-scalable=no, viewport-fit=cover" />

        <meta name="description" content="" />

        {/* Open Graph / Facebook */}
        <meta property="og:type" content="website" />
        <meta property="og:url" content="/" />
        <meta property="og:title" content="" />
        <meta property="og:description" content="" />
        <meta property="og:image" content="" />
        <meta property="og:site_name" content="aceMedia" />

        {/* Twitter */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:url" content="" />
        <meta name="twitter:title" content="aceMedia" />
        <meta name="twitter:description" content="" />
        <meta name="twitter:image" content="" />
    </head>
      <body className="index-page">
      <SiteHeader
          siteName={siteSettings.siteName}
          navItems={siteSettings.navItems}
          socialLinks={siteSettings.socialLinks}
          profileImageUrl={siteSettings.profileImage?.url ?? '/studio-ghibli.png'}
      />

      <main className={'main'}>
          {children}
      </main>

      <SiteFooter copyrightName={siteSettings.footerCopyrightName} />
      </body>
    </html>
  );
}
